2022-05-26 16:01:57,250 INFO    MainThread:18067 [internal.py:wandb_internal():90] W&B internal server running at pid: 18067, started at: 2022-05-26 16:01:57.249836
2022-05-26 16:01:57,251 INFO    WriterThread:18067 [datastore.py:open_for_write():75] open: /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220526_160156-2kldoraa/run-2kldoraa.wandb
2022-05-26 16:01:57,252 DEBUG   SenderThread:18067 [sender.py:send():232] send: header
2022-05-26 16:01:57,252 DEBUG   SenderThread:18067 [sender.py:send():232] send: run
2022-05-26 16:01:57,427 DEBUG   HandlerThread:18067 [handler.py:handle_request():141] handle_request: check_version
2022-05-26 16:01:57,439 INFO    SenderThread:18067 [dir_watcher.py:__init__():197] watching files in: /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220526_160156-2kldoraa/files
2022-05-26 16:01:57,439 INFO    SenderThread:18067 [sender.py:_start_run_threads():811] run started: 2kldoraa with start time 1653595316
2022-05-26 16:01:57,439 DEBUG   SenderThread:18067 [sender.py:send():232] send: summary
2022-05-26 16:01:57,439 INFO    SenderThread:18067 [sender.py:_save_file():948] saving file wandb-summary.json with policy end
2022-05-26 16:01:57,439 DEBUG   SenderThread:18067 [sender.py:send_request():246] send_request: check_version
2022-05-26 16:01:57,523 DEBUG   HandlerThread:18067 [handler.py:handle_request():141] handle_request: run_start
2022-05-26 16:01:57,526 DEBUG   HandlerThread:18067 [meta.py:__init__():35] meta init
2022-05-26 16:01:57,526 DEBUG   HandlerThread:18067 [meta.py:__init__():49] meta init done
2022-05-26 16:01:57,526 DEBUG   HandlerThread:18067 [meta.py:probe():209] probe
2022-05-26 16:01:57,529 DEBUG   HandlerThread:18067 [meta.py:_setup_git():199] setup git
2022-05-26 16:01:58,252 INFO    WriterThread:18067 [datastore.py:close():279] close: /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220526_160156-2kldoraa/run-2kldoraa.wandb
2022-05-26 16:01:58,443 INFO    Thread-7  :18067 [dir_watcher.py:_on_file_created():244] file/dir created: /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220526_160156-2kldoraa/files/wandb-summary.json
2022-05-26 16:01:58,510 INFO    SenderThread:18067 [sender.py:finish():1110] shutting down sender
2022-05-26 16:01:58,510 INFO    SenderThread:18067 [dir_watcher.py:finish():312] shutting down directory watcher
2022-05-26 16:01:59,444 INFO    SenderThread:18067 [dir_watcher.py:finish():342] scan: /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220526_160156-2kldoraa/files
2022-05-26 16:01:59,444 INFO    SenderThread:18067 [dir_watcher.py:finish():356] scan save: /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220526_160156-2kldoraa/files/config.yaml config.yaml
2022-05-26 16:01:59,444 INFO    SenderThread:18067 [dir_watcher.py:finish():356] scan save: /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220526_160156-2kldoraa/files/wandb-summary.json wandb-summary.json
2022-05-26 16:01:59,444 INFO    SenderThread:18067 [file_pusher.py:finish():145] shutting down file pusher
2022-05-26 16:01:59,444 INFO    SenderThread:18067 [file_pusher.py:join():150] waiting for file pusher
2022-05-26 16:01:59,879 INFO    Thread-11 :18067 [upload_job.py:push():132] Uploaded file /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220526_160156-2kldoraa/files/config.yaml
2022-05-26 16:01:59,974 INFO    Thread-12 :18067 [upload_job.py:push():132] Uploaded file /D/MIT-WHOI/github_repos/syn_model/scripts/wandb/run-20220526_160156-2kldoraa/files/wandb-summary.json
2022-05-26 16:02:00,521 ERROR   MainThread:18067 [internal.py:wandb_internal():165] Thread HandlerThread:
Traceback (most recent call last):
  File "/home/miras/anaconda3/envs/sklearn/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 51, in run
    self._run()
  File "/home/miras/anaconda3/envs/sklearn/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/home/miras/anaconda3/envs/sklearn/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 265, in _process
    self._hm.handle(record)
  File "/home/miras/anaconda3/envs/sklearn/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 133, in handle
    handler(record)
  File "/home/miras/anaconda3/envs/sklearn/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 143, in handle_request
    handler(record)
  File "/home/miras/anaconda3/envs/sklearn/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 672, in handle_request_run_start
    run_meta.probe()
  File "/home/miras/anaconda3/envs/sklearn/lib/python3.10/site-packages/wandb/sdk/internal/meta.py", line 230, in probe
    self._setup_git()
  File "/home/miras/anaconda3/envs/sklearn/lib/python3.10/site-packages/wandb/sdk/internal/meta.py", line 205, in _setup_git
    self.data["root"] = self._git.root or self.data["root"] or os.getcwd()
  File "/home/miras/anaconda3/envs/sklearn/lib/python3.10/site-packages/wandb/sdk/lib/git.py", line 46, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/home/miras/anaconda3/envs/sklearn/lib/python3.10/site-packages/git/cmd.py", line 639, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/miras/anaconda3/envs/sklearn/lib/python3.10/site-packages/git/cmd.py", line 1184, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/miras/anaconda3/envs/sklearn/lib/python3.10/site-packages/git/cmd.py", line 984, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: unsafe repository ('/D/MIT-WHOI/github_repos/syn_model' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /D/MIT-WHOI/github_repos/syn_model'
2022-05-26 16:02:02,533 INFO    MainThread:18067 [internal.py:handle_exit():80] Internal process exited
